name: Deploy to prod env
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Production version'     
        required: true
        default: 'v0.0.1'
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: yarn

        - name: Build
          run: yarn build

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket: ${{ secrets.AWS_PROD_BUCKET }}
            bucket-region: ${{ secrets.AWS_REGION }}
            invalidation: /
            delete-removed: true
            no-cache: true
            filesToInclude: ".*/*,*/*,**"
